name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
      - name: Init SSHKEY
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" >  ~/.ssh/ssh_key
         ssh-add ~/.ssh/ssh_key
      - name: Deploy
        run:  
         scp -r ${{ secrets.SSH_PRIVATE_KEY }} build said@51.178.30.100:/home/said

